### ISSUE TITLE
Curso de Python 3 - Mundo 1: Fundamentos

### ISSUE THREAD

**Issue by vgoes001** [vgoes001/-Curso-em-V-deo---Python---M-dulo-1#1]
- [ ] Curso Python #01 - Seja um Programador
- [ ] Curso Python #02 - Para que serve o Python?
- [ ] Curso Python #03 - Instalando o Python3 e o IDLE
- [ ] Curso Python #04 - Primeiros comandos em Python3
